name: Build and Run Docker

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lango .

      - name: Minio - Interpret example file
        run: docker run -it --rm lango run --input_file examples/minio/example.minio

      - name: Minio - Compile example file
        run: docker run -it --rm lango compile examples/minio/example.minio
