name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install GHC
        run: |
          sudo apt-get update
          sudo apt-get install -y ghc
      - name: Create virtual environment
        run: make prep
      - uses: pre-commit/action@v3.0.1
